<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageTags>configuration;localization;commands;winforms</PackageTags>
    <AssemblyVersion></AssemblyVersion>
    <Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Coding4Coffee.Basics" Version="1.0.1" />
  </ItemGroup>

</Project>
