<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<PackageTags>configuration;localization;commands;winforms</PackageTags>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<LicenseExpression>MIT</LicenseExpression>
	<AssemblyVersion></AssemblyVersion>
	<Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Coding4Coffee.Basics\Coding4Coffee.Basics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
